services:
  - type: web
    name: onehealth-backend
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: FLASK_DEBUG
        value: "False"
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: MOCK_MODE
        value: "True"
      - key: FIREBASE_CREDENTIALS_PATH
        value: serviceAccountKey.json
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
